// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========

// git prints usage errors at tree levels with exit 129; leaf spec errors
// keep the GNU exit-2 machinery they already ride.
export const USAGE_EXIT = 129

// The environment variable carrying an install's config to a script CLI
// (JSON). Deliberately not MIRAGE_CONFIG: that one already names the
// workspace config file for the server and mcp entry points, and a
// script CLI that shells back into mirage must not find a config blob
// where a path belongs.
export const CLI_CONFIG_ENV = 'MIRAGE_CLI_CONFIG'

// clap exits 2 for a usage error at every level of its tree, agreeing with
// argparse by coincidence rather than by lineage. It lives here rather than
// beside the refusal renderers because the walk reads it too, and the walk
// cannot import a module that reaches the workspace.
export const CLAP_EXIT = 2

// git's own long options for each parse-options verb mirage implements, in
// git's table order and its `--[no-]` notation, captured from
// `git <verb> --help-all` (config's legacy table from its usage listing) on
// git 2.50.1. Under git's usage style a leaf resolves an abbreviated long
// option against its verb's table the way parse-options does, so a prefix git
// finds ambiguous is refused even where mirage declares only one of the
// options it could be. A git verb with no table (log, show, diff, rev-list,
// diff-tree: the revision walkers) takes whole words only, as git's revision
// parser does.
export const GIT_LONG_OPTIONS: ReadonlyMap<string, readonly string[]> = new Map([
  [
    'add',
    [
      '[no-]dry-run',
      '[no-]verbose',
      '[no-]interactive',
      '[no-]patch',
      '[no-]edit',
      '[no-]force',
      '[no-]update',
      '[no-]renormalize',
      '[no-]intent-to-add',
      '[no-]all',
      '[no-]ignore-removal',
      '[no-]refresh',
      '[no-]ignore-errors',
      '[no-]ignore-missing',
      '[no-]sparse',
      '[no-]chmod',
      '[no-]warn-embedded-repo',
      '[no-]pathspec-from-file',
      '[no-]pathspec-file-nul',
    ],
  ],
  [
    'branch',
    [
      '[no-]verbose',
      '[no-]quiet',
      '[no-]track',
      '[no-]set-upstream',
      '[no-]set-upstream-to',
      '[no-]unset-upstream',
      '[no-]color',
      'remotes',
      'contains',
      'no-contains',
      'with',
      'without',
      '[no-]abbrev',
      'all',
      '[no-]delete',
      '[no-]move',
      '[no-]omit-empty',
      '[no-]copy',
      '[no-]list',
      '[no-]show-current',
      '[no-]create-reflog',
      '[no-]edit-description',
      '[no-]force',
      'merged',
      'no-merged',
      '[no-]column',
      '[no-]sort',
      '[no-]points-at',
      '[no-]ignore-case',
      '[no-]recurse-submodules',
      '[no-]format',
    ],
  ],
  [
    'checkout',
    [
      '[no-]guess',
      '[no-]overlay',
      '[no-]quiet',
      '[no-]recurse-submodules',
      '[no-]progress',
      '[no-]merge',
      '[no-]conflict',
      '[no-]detach',
      '[no-]track',
      '[no-]force',
      '[no-]orphan',
      '[no-]overwrite-ignore',
      '[no-]ignore-other-worktrees',
      'ours',
      'theirs',
      '[no-]patch',
      '[no-]ignore-skip-worktree-bits',
      '[no-]pathspec-from-file',
      '[no-]pathspec-file-nul',
    ],
  ],
  [
    'commit',
    [
      '[no-]quiet',
      '[no-]verbose',
      '[no-]file',
      '[no-]author',
      '[no-]date',
      '[no-]message',
      '[no-]reedit-message',
      '[no-]reuse-message',
      '[no-]fixup',
      '[no-]squash',
      '[no-]reset-author',
      'trailer',
      '[no-]signoff',
      '[no-]template',
      '[no-]edit',
      '[no-]cleanup',
      '[no-]status',
      '[no-]gpg-sign',
      '[no-]all',
      '[no-]include',
      '[no-]interactive',
      '[no-]patch',
      '[no-]only',
      'no-verify',
      'verify',
      '[no-]dry-run',
      '[no-]short',
      '[no-]branch',
      '[no-]ahead-behind',
      '[no-]porcelain',
      '[no-]long',
      '[no-]null',
      '[no-]amend',
      'no-post-rewrite',
      'post-rewrite',
      '[no-]untracked-files',
      '[no-]pathspec-from-file',
      '[no-]pathspec-file-nul',
      '[no-]allow-empty',
      '[no-]allow-empty-message',
    ],
  ],
  [
    'config',
    [
      '[no-]global',
      '[no-]system',
      '[no-]local',
      '[no-]worktree',
      '[no-]file',
      '[no-]blob',
      'get',
      'get-all',
      'get-regexp',
      'get-urlmatch',
      'replace-all',
      'add',
      'unset',
      'unset-all',
      'rename-section',
      'remove-section',
      'list',
      'edit',
      'get-color',
      'get-colorbool',
      '[no-]null',
      '[no-]name-only',
      '[no-]show-origin',
      '[no-]show-scope',
      '[no-]show-names',
      '[no-]type',
      'bool',
      'int',
      'bool-or-int',
      'bool-or-str',
      'path',
      'expiry-date',
      '[no-]default',
      '[no-]comment',
      '[no-]fixed-value',
      '[no-]includes',
    ],
  ],
  ['mv', ['[no-]verbose', '[no-]dry-run', '[no-]force', '[no-]sparse']],
  ['remote', ['[no-]verbose']],
  [
    'reset',
    [
      '[no-]quiet',
      'no-refresh',
      'refresh',
      'mixed',
      'soft',
      'hard',
      'merge',
      'keep',
      '[no-]recurse-submodules',
      '[no-]patch',
      '[no-]intent-to-add',
      '[no-]pathspec-from-file',
      '[no-]pathspec-file-nul',
    ],
  ],
  [
    'restore',
    [
      '[no-]source',
      '[no-]staged',
      '[no-]worktree',
      '[no-]ignore-unmerged',
      '[no-]overlay',
      '[no-]quiet',
      '[no-]recurse-submodules',
      '[no-]progress',
      '[no-]merge',
      '[no-]conflict',
      'ours',
      'theirs',
      '[no-]patch',
      '[no-]ignore-skip-worktree-bits',
      '[no-]pathspec-from-file',
      '[no-]pathspec-file-nul',
    ],
  ],
  [
    'rm',
    [
      '[no-]dry-run',
      '[no-]quiet',
      '[no-]cached',
      '[no-]force',
      '[no-]ignore-unmatch',
      '[no-]sparse',
      '[no-]pathspec-from-file',
      '[no-]pathspec-file-nul',
    ],
  ],
  [
    'show-ref',
    [
      '[no-]tags',
      '[no-]branches',
      '[no-]heads',
      '[no-]exists',
      '[no-]verify',
      '[no-]head',
      '[no-]dereference',
      '[no-]hash',
      '[no-]abbrev',
      '[no-]quiet',
      'exclude-existing',
    ],
  ],
  [
    'status',
    [
      '[no-]verbose',
      '[no-]short',
      '[no-]branch',
      '[no-]show-stash',
      '[no-]ahead-behind',
      '[no-]porcelain',
      '[no-]long',
      '[no-]null',
      '[no-]untracked-files',
      '[no-]ignored',
      '[no-]ignore-submodules',
      '[no-]column',
      'no-renames',
      'renames',
      'find-renames',
    ],
  ],
  [
    'switch',
    [
      '[no-]create',
      '[no-]force-create',
      '[no-]guess',
      '[no-]discard-changes',
      '[no-]quiet',
      '[no-]recurse-submodules',
      '[no-]progress',
      '[no-]merge',
      '[no-]conflict',
      '[no-]detach',
      '[no-]track',
      '[no-]force',
      '[no-]orphan',
      '[no-]overwrite-ignore',
      '[no-]ignore-other-worktrees',
    ],
  ],
  [
    'tag',
    [
      'list',
      'delete',
      'verify',
      '[no-]annotate',
      'message',
      '[no-]file',
      'trailer',
      '[no-]edit',
      '[no-]sign',
      '[no-]cleanup',
      '[no-]local-user',
      '[no-]force',
      '[no-]create-reflog',
      '[no-]column',
      'contains',
      'no-contains',
      'with',
      'without',
      'merged',
      'no-merged',
      '[no-]omit-empty',
      '[no-]sort',
      '[no-]points-at',
      '[no-]format',
      '[no-]color',
      '[no-]ignore-case',
    ],
  ],
  ['version', ['[no-]build-options']],
])
